FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci && npm i -g vite

COPY env.production .env

COPY . .

ENV PATH /app/node_modules/.bin:$PATH

RUN npm run build

FROM node:20-slim AS runner

COPY --from=builder /app/dist ./

EXPOSE 3000

CMD ["serve", "-s", ".", "-l", "3000"]